### ISSUE TITLE
clang -Wbitwise-instead-of-logical

### ISSUE THREAD

**Issue by tuero** [CommitThis/zip-iterator#2]
https://github.com/CommitThis/zip-iterator/blob/8d1362e82577b210e8bc5d9de793aa25fe35aae2/zip_tuple.hpp#L28

Clang gives a warning on the above line. Shouldn't local or `||` be used here instead of bitwise `|`? If so, I can send a PR to fix.

**Comment by CommitThis** [comment]
Hi Jake, thanks for reviewing. You're right, a pull request would be
welcomed!
